relativeURLs = true
# baseURL = 'https://felixkaspar.com/new/'
# canonifyurls = true

languageCode = 'en-us'
title = 'Felix Kaspar'
theme = "theme"

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "fa-solid fa-house"
    url = "/#"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "fa-solid fa-id-card"
    url = "/#about"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pre = "fa-solid fa-list-check"
    url = "/#projects"
    weight = 3
  [[menu.main]]
    name = "Blog"
    pre = "fa-solid fa-book"
    url = "/#blog"
    weight = 4

[taxonomies]
    project = 'projects'
    tag = 'tags'